// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uifolpnnlyyhzeusivge.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVpZm9scG5ubHl5aHpldXNpdmdlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzcwMTYyMzYsImV4cCI6MjA1MjU5MjIzNn0.v9Iipm3DrwR8rE1V3piL8fUnQKgry9T5rNA-JOEhMPE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);